### ISSUE TITLE
The 4.14 kernel has been upgraded to 4.14.27

### ISSUE THREAD

**Issue by kunxiang1** [Nossiac/mtk-openwrt-feeds#42]
Could you update it?Right now only compiled 4.14.23. There is also a suggestion that pre-compiled ko files can keep only the latest, and the previous version can be deleted, so that there will not be too many reserved files.

**Comment by Nossiac** [comment]
Already done. Actually the lastest kernel has already bumped to 4.14.29 last weekend.

My autobuild service builds those modules every week for :

- latest lede-17.01 (branch latest)
- latest lede-17.01.4 (tagged version)
- latest master with 4.9.x (branch latest)
- latest master with 4.14.x (not officially launched yet, need to alter the config)

The service accidently stoped because my server ran out of storage last week. After some clean up, it restarts.
